/*******************************************************************************
 * app_tasks.h
 * NGE Scheduler – shared application task declarations
 *
 * Three demonstration tasks are defined identically for every port:
 *
 *  HeartbeatTask  Periodic: toggles the platform LED / stdout marker every
 *                 500 ticks.  Demonstrates lTimer-based periodic events.
 *
 *  CommTask       Event-driven: processes incoming data frames queued by the
 *                 BSP receive ISR.  Demonstrates one-shot NORMAL events with
 *                 a payload pointer.
 *
 *  MonitorTask    Delayed one-shot: runs a self-test 200 ticks after start-up,
 *                 then re-arms itself for the next 1000-tick window.
 *                 Demonstrates manual re-arming via ADD_EVENT.
 *
 * Each port's main.c calls:
 *   initHeartbeatTask();
 *   initCommTask();
 *   initMonitorTask();
 * then enters SchEventManager(aTaskArray).
 ******************************************************************************/

#ifndef APP_TASKS_H
#define APP_TASKS_H

#include "NGE_Scheduler.h"

/*******************************************************************************
 * Application message IDs  (must be >= EVT_APP_BASE)
 ******************************************************************************/
#define MSG_HEARTBEAT    ((u16)EVT_APP_BASE + 0U)
#define MSG_COMM_RX      ((u16)EVT_APP_BASE + 1U)
#define MSG_MONITOR      ((u16)EVT_APP_BASE + 2U)

/*******************************************************************************
 * Extended event types  (concrete event types that extend tEvent)
 ******************************************************************************/

/* CommTask event carries a data buffer and a byte count. */
typedef struct
{
    tEvent base;               /* MUST be the first member (Rule 18.1)      */
    uint8_t  aData[16];        /* Received data payload                     */
    uint8_t  uLen;             /* Number of valid bytes in aData            */
} tCommEvent;

/*******************************************************************************
 * Task forward declarations
 * init<TaskName>() is generated by SCH_TSK_CREATE2 in app_tasks.c.
 ******************************************************************************/
extern tTask *HeartbeatTask;
extern tTask *CommTask;
extern tTask *MonitorTask;

eTskStatus initHeartbeatTask(void);
eTskStatus initCommTask(void);
eTskStatus initMonitorTask(void);

/*******************************************************************************
 * BSP callback: called by the port's BSP when a frame arrives.
 ******************************************************************************/
void App_OnFrameReceived(const uint8_t *pData, uint8_t uLen);

#endif /* APP_TASKS_H */
