/*******************************************************************************
 * ports/renesas_rh850/bsp/bsp.h
 * NGE Scheduler – BSP for Renesas RH850/U2A (G4MH core)
 *
 * Tick source    : OSTM0 (OS Timer 0) in interval mode, 1 ms period.
 *                  Assumes PCLK = 80 MHz → reload = 80 000 - 1.
 * Critical section : RH850 DI / EI instructions via intrinsics.
 * LED            : P10_0 (generic; adapt to your eval board).
 *
 * Toolchain: CCRH850 (Renesas CC-RH) or GHS Multi
 * Header  : iodefine.h generated by e² studio for the target device.
 ******************************************************************************/
#ifndef BSP_H
#define BSP_H

#include <stdint.h>
#include "iodefine.h"   /* Renesas device register header – MCU-specific */

/* RH850 global interrupt disable/enable via compiler intrinsics. */
#if defined(__CCRH__)
#  include <intrinsics.h>
#  define SCH_ENTER_CRITICAL()  __DI()
#  define SCH_EXIT_CRITICAL()   __EI()
#elif defined(__ghs__)
#  define SCH_ENTER_CRITICAL()  __asm(" di")
#  define SCH_EXIT_CRITICAL()   __asm(" ei")
#else
#  define SCH_ENTER_CRITICAL()  /* fallback – override for your toolchain */
#  define SCH_EXIT_CRITICAL()
#endif

#include "NGE_Scheduler.h"

#define BSP_PCLK_HZ       (80000000UL)
#define BSP_TICK_HZ       (1000UL)
#define BSP_OSTM0_RELOAD  ((BSP_PCLK_HZ / BSP_TICK_HZ) - 1UL)   /* 79 999 */

void BSP_Init(void);
void BSP_ToggleLED(void);
void BSP_PrintLine(const char *pStr);

#endif /* BSP_H */
